name: Linting

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Poetry
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.7.1
          $POETRY_HOME/bin/poetry --version

      - name: Install dev packages
        run: /opt/poetry/bin/poetry install -n -v

      - name: Lint with flakeheaven
        run: |
          export PATH="/opt/poetry/bin:$PATH"
          poetry run pre-commit run --all-files
