name: Publish Python distributions 📦 to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish Python distributions 📦 to PyPI repo
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Poetry
        run: |
          export POETRY_HOME=/opt/poetry
          python3 install-poetry.py --version 1.2.0
          $POETRY_HOME/bin/poetry --version

      - name: Build and publish package
        run: |
          /opt/poetry/bin/poetry config pypi-token.pypi "${{ secrets.pypi_password }}"
          /opt/poetry/bin/poetry publish -n --build
